invoice:
    resource:
        path: ../src/Invoice/Controller/
        namespace: App\Invoice\Controller
    type: attribute
dashboard:
    resource:
        path: ../src/Dashboard/Controller/
        namespace: App\Dashboard\Controller
    type: attribute
